# Generated by Django 3.0.8 on 2020-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('date_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('test_type', models.CharField(choices=[('RT-PCR', 'RT-PCR'), ('Sorologia', 'Sorologia'), ('Teste Rápido - Antígenos', 'Teste Rápido - Antígenos'), ('Teste Rápido - Anticorpos', 'Teste Rápido - Anticorpos')], max_length=26, verbose_name='Tipo de Teste')),
                ('result', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=25, verbose_name='Resultado')),
            ],
        ),
    ]
